-- Generated by Oracle SQL Developer Data Modeler 4.1.5.907
--   at:        2018-04-29 13:41:38 AEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g




create
  table book
  (
    callno           number (20) not null ,
    authorname       varchar2 (50) ,
    subject          varchar2 (50) ,
    language         varchar2 (20) ,
    purchaseprice    number (10) ,
    classification   varchar2 (20) ,
    pages            number (5) ,
    copy_barcode     number (20) not null ,
    copy_callno      number (20) not null ,
    callno11         number not null ,
    publisher_callno number (20) not null
  ) ;

alter table book add constraint book_pk primary key ( callno ) ;


create
  table borrower
  (
    borrowernumber         number not null ,
    borrowerhomebranch     varchar2 (20) ,
    borrowername           varchar2 (50) ,
    borroweraddress        varchar2 (100) ,
    borrowerclassification varchar2 (10)
  ) ;

alter table borrower add constraint borrower_pk primary key ( borrowernumber )
;


create
  table copy
  (
    copystatus              varchar2 (50) not null ,
    barcode                 number (20) not null ,
    callno                  number (20) not null ,
    isbn                    number (13) ,
    copytype                varchar2 (50) ,
    borrower_borrowernumber number not null
  ) ;


create unique index copy__idx on copy
  (
    borrower_borrowernumber asc
  )
  ;

alter table copy add constraint copy_pk primary key ( barcode, callno ) ;


create
  table loan
  (
    barcode                 number (20) not null ,
    borrowernumber          number (7) not null ,
    loancurrentdate         date ,
    loanreturnactualdate    date ,
    loanreserveorder        number (20) ,
    paymentdate             date ,
    borrower_borrowernumber number not null ,
    copy_barcode            number (20) not null ,
    copy_callno             number (20) not null ,
    callno1                 number not null
  ) ;

alter table loan add constraint loan_pk primary key ( barcode, borrowernumber )
;


create
  table branch
  (
    branchcode        number (3) not null ,
    branchname        varchar2 (10) ,
    branchaddress     varchar2 (50) ,
    branchphone       number (10) ,
    managerid         number (5) ,
    manager_managerid number (5) ,
    copy_barcode      number (20) not null ,
    copy_callno       number (20) not null ,
    callno1           number not null
  ) ;

alter table branch add constraint branch_pk primary key ( branchcode ) ;


create
  table manager
  (
    managerid    number (5) not null ,
    managername  varchar2 (10) ,
    managerphone number (10) ,
    homebranch   varchar2 (50)
  ) ;

alter table manager add constraint manager_pk primary key ( managerid ) ;


create
  table publisher
  (
    callno        number (20) not null ,
    title         varchar2 (50) ,
    description   varchar2 (50) ,
    publishername varchar2 (50) ,
    edition       number (3) ,
    publishyear   number (5)
  ) ;

alter table publisher add constraint publisher_pk primary key ( callno ) ;



alter table book add constraint book_copy_fk foreign key ( copy_barcode,
copy_callno ) references copy ( barcode, callno ) ;


alter table book add constraint book_publisher_fk foreign key (
publisher_callno ) references publisher ( callno ) ;


alter table copy add constraint copy_borrower_fk foreign key (
borrower_borrowernumber ) references borrower ( borrowernumber ) ;


alter table loan add constraint loan_borrower_fk foreign key (
borrower_borrowernumber ) references borrower ( borrowernumber ) ;


alter table loan add constraint loan_copy_fk foreign key ( copy_barcode,
copy_callno ) references copy ( barcode, callno ) ;


alter table branch add constraint branch_copy_fk foreign key ( copy_barcode,
copy_callno ) references copy ( barcode, callno ) ;


alter table branch add constraint branch_manager_fk foreign key (
manager_managerid ) references manager ( managerid ) ;


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             1
-- ALTER TABLE                             14
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
